spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/study;MODE=MYSQL
    username: sa
    password: 123
    driver: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: /mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.flab.toyboardproject
